### PR TITLE
docs: Enforce prose wrap in prettier for markdown files

### PR DESCRIPTION
**Pull request by avaly**
Let's enforce the max line length on the Markdown files as well through Prettier.

### CODE REVIEW

**Comment by ejmartin504** [comment]
Since it's automatic, I don't really have an issue with this, but it does seem kind of strange to enforce. As others have pointed out the last time forced wrapping came up, if you are viewing the output of a markdown, wherever you are viewing it (e.g. GH) will automatically enforce wrapping around the viewport, so artificially wrapping the source files based on something like terminal width doesn't seem like a huge win for me, personally 🤷

**Review by vanstinator — COMMENTED** [review]
How does this impact rendering the output if the viewport is wider than the MD width? Is the renderer going to unwrap the lines _anyway_ and render them accordingly, or is this going to make the output funkier.

**Comment by avaly** [comment]
Indeed, it does show up weird in a Github diff view. Maybe we skip it for now.

**Comment by ejmartin504** [comment]
For posterity, the case against line-lengths was made by a fellow Plexian (@alexjsp) and I thought it was worth quoting here:

>  it ignores the fact text will be shown in different places, different styles. And completely ignores accessibility needs like larger fonts that might make the line length that’s been arbitrarily chosen unworkable.

image (2)

**Pull request closed without merging**
