### PR TITLE
refactor: Remove default schema `__v` version property

### PR DESCRIPTION
**Pull request by joshuat**
This is an opinionated PR but certainly not something I have strong feelings about. 

I appreciate that Papr is, first and foremost, a library created by Plex for their use case, which is undoubtedly very common considering the prominence of Mongoose, but in my opinion, we should consider dropping the hardcoded `__v` property from schema definitions.

A bit of background: the `__v` property is the [`versionKey`](https://mongoosejs.com/docs/guide.html#versionKey) default supplied by Mongoose. Papr adds this property to all schemas by default to support an easy migration from Mongoose. However, this doesn't take into account users who are not migrating from Mongoose (or have changed their `versionKey` value prior to migrating).

I think the better option for those who want to support data migrated from Mongoose would be to have them add `__v` to their schema definition. This is more boilerplate for every schema, but it gives more flexibility and produces more accurate type data for everyone, including those who would choose not to have the `versionKey` present at all.

While all the points I made above are true, it is also worth highlighting that the property added to all schemas is optional, meaning while we do receive incorrect types, we're not at risk of inadvertent schema validation errors.

BREAKING CHANGE: Schemas no longer have a default `__v` property defined. Users who have migrated from Mongoose or are otherwise taking advantage of this property will have to manually add it to their schema definitions.

### CODE REVIEW

**Review by ejmartin504 — DISMISSED** [review]
100% agree with this change! We added this property while doing our own internal migration, but I don't think it ever needed to be in the published package. 👍

**Comment by sullman** [comment]
Agreed!

That said, do you think mongoose->papr is a common enough scenario to want to support that it'd be worth making it slightly simpler by adding something to `SchemaOptions`? I'm thinking along the lines of:

```
{
  timestamps: true,
  version: true
}
```

It's not fewer lines of code as a user of papr, and it's more to maintain in the library, but it might be slightly friendlier. No strong feelings here though.

**Comment by joshuat** [comment]
@sullman if Papr were maintaining the version of records then I would agree, but since the schema option would just be to add a static schema property I would vote against that (if only because implementing it from a type perspective is somewhat more difficult)

**Comment by avaly** [comment]
I agree that we should just remove this legacy support.

It would be nice to have an option in the schema, but like @joshuat mentioned, it's more cumbersome to add proper type support for it, then the benefit it would bring.

The simple alternative for folks migrating from Mongoose to Papr will just be to add this single line of code in each of their collections. While of course the proper workaround would be to just remove that data completely from their collections.

**Comment by avaly** [comment]
@joshuat Together with this change, let's add a small section in our docs mentioning required steps for folks migrating from Mongoose. Maybe under the `Recipies` section?

**Comment by joshuat** [comment]
@avaly That sounds like a good idea. Sorry for the late response, just getting back from some time off. I'll get that documentation added to this PR today.

**Review by ejmartin504 — APPROVED** [review]
Wow, this documentation is superb! Thank you so much for taking the time to write it!

**Review by avaly — APPROVED** [review]
Indeed! Awesome work on those docs!!!

**Pull request merged**
